### ISSUE TITLE
Tracking Issue for the VSCode extension republish

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#11987]
Tasks we can do right now:
 - [x] Verify the `rust-lang` publisher: https://github.com/rust-lang/rust-analyzer/issues/11978#issuecomment-1098940863

Tasks that have to happen somewhat simultaneously:
 - [x] Fix the config format: https://github.com/rust-lang/rust-analyzer/pull/12010
 - [x] Get in touch with the vscode marketplace team to initiate the move
    > Yes, we can move the extension. For that the author of the extension needs to send an email to vsmarketplace@microsoft.com and me inikolic@microsoft.com and we can do the rest.
 - [x] Fix up CI to publish under the correct publisher
 - [x] Fixup remaining links to the old marketplace extension

**Comment by rylev** [comment]
I believe another todo item here should be to update the tagline for [the extension](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) which still says "An alternative rust language server to the RLS".
