### ISSUE TITLE
Tracking issue for `ide-completion` refactor

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#12144]
In https://github.com/rust-lang/rust-analyzer/pull/11397 I started refactoring the completions crate a bit and I haven't gotten back to finishing this up, so the crate is in a weird state where we use 3 differnt things to determine where certain completions apply. So with this I'll write down what I had in mind and where we are currently at in regards to that plan.

Completions are generated by fist calculating a [`CompletionContext`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/context.rs#L136) which analyzes the surrounding context of the cursor position which we can then derive the completions from. Following that we just execute a bunch of functions that fill the completions accumulator with completions.
https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/lib.rs#L150-L173
The here was to have a function calculating completions for a specific "thing", this "thing" varies widely as to what it applies though. My goal with the refactor was to make this "thing" more consistent in what it covers.

We can group the things we actually complete into roughly the following:
- keywords
- `Name`s
- `Lifetime`s
- `NameRef`s (paths and a few exceptios)
- snippets
- very specialized things (string literals, fmt strings, ...)

Obviously grouping the completion generation by just these is too rough, we want to do it differently. Completing by `Name`s and `NameRef`s alone is messy, as we need to know about the context of where we are completing in (are we inside a type position, expression position, function return type, etc...), but this is what we kind of are doing right now if you take a look at the [unqualified path](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/unqualified_path.rs) module or the [qualfied path](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/qualified_path.rs) module (these are practically the `NameRef` case). There are a bunch of different checks regarding where we are currently at placed around at various places making the code a mess.

So what I instead envision is for us to split these modules apart according to their position they apply to, with branches for the different thinsg that can be completed there (with a few exceptions for special completions). I've started with this for paths, where I have split out [attributes](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/completions/attribute.rs#L71), [visibility paths](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/vis.rs), [use paths](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/use_.rs) and [pattern paths](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/pattern.rs#L107-L208).
This structure allows one to more easily reason about what completions apply where.

This refactor should get us closer to do "perfect completions".

I'll fully fill out the list of finer grained tasks here later this week:
- [x] Split apart [unqualfied path]https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/unqualified_path.rs) and [qualfied path](https://github.com/rust-lang/rust-analyzer/blob/0ee4e6a22d79f58b6b459dbc874d6b90a4495d83/crates/ide-completion/src/completions/qualified_path) into the remaining variants
  - [x] Expressions / Statements
  - [x] Type
  - [x] Derive
  - [x] Attribute
  - [x] Visibility
  - [x] Pattern
  - [x] Use
  - [x] ItemList / AssocItemList (module and sourcefile / trait and impl, macro calls can appear there)
- [x] Split up keyword module
  - [ ] Implement proper keyword completions for items, respecting their order and similar. That is in `unsafe const $0` we should only propose `fn`, not `const` or `unsafe` again.
- [ ] Properly handle completions in generic argument position, currently its offered via type path completions with some special cases...
- [x] Split flyimport into the corresponding modules, this should probably be done last. We need to verify that the modules doing flyimport are disjoint so we don't do this multiple times.
- [x] Remove [`is_path_disallowed`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/context.rs#L372) and other `CompletionContext` functions that look like temporary hacks.

**Comment by Veykril** [comment]
With https://github.com/rust-lang/rust-analyzer/pull/12560 https://github.com/rust-lang/rust-analyzer/pull/12565 https://github.com/rust-lang/rust-analyzer/pull/12564 https://github.com/rust-lang/rust-analyzer/pull/12562 and https://github.com/rust-lang/rust-analyzer/pull/12573 the main refactors in this issue are now done.

I've split the two other checkboxes into separate issues as htey are less of a refactoring task and more of an implementation thing, https://github.com/rust-lang/rust-analyzer/issues/12567 https://github.com/rust-lang/rust-analyzer/issues/12568

The last refactor we need to do now is https://github.com/rust-lang/rust-analyzer/issues/12571 and then we should have reached a state where we can perfect our completions on
