### ISSUE TITLE
[Tracking issue] rust-analyzer in-tree build prerequisites

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/rust-analyzer#12818]
The rationale for "why move from submodule to subtree" is in:

  * #12815

The proof of concept PR is here:

 * https://github.com/rust-lang/rust/pull/99465

This is a list of what needs to happen before `rust-analyzer` the _real_ `rust-lang/rust` PR to re-add it as a subtree can happen:

  * [x] https://github.com/rust-lang/rust-analyzer/pull/12826
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12828
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12829
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12831
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12833
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12834
  * [x] https://github.com/rust-lang/rust-analyzer/pull/12835

I'll expand the list until the research PR passes in CI, and try to land all these changes as separate rust-analyzer PRs.

**Comment by fasterthanlime** [comment]
All of these have landed, I'm moving on to making a subtree PR to `rust-lang/rust`!
