### ISSUE TITLE
Assists that should really be diagnostics quickfix

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14262]
We have a few assists that actually take the role of quickfixes of diagnostics, but haven't been implemented as such because of simplicity or due to us not having the diagnostic infra for it yet. We should make an effort into implementing the corresponding diagnostics and transitioning them towards becoming quickfixes for said diagnostics where applicable.

The following assists should be turned into quickfixes for diagnostics (fully or partially):
- [ ] [add_lifetime_to_type](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/add_lifetime_to_type.rs)
	- [ ] diagnostic implemented 
- [ ] [add_impl_missing_members](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/add_missing_impl_members.rs)
	- [ ] diagnostic implemented 
	- Note that only `add_impl_missing_members` is a diagnostic quickfix, `add_impl_default_members` will remain an assist
- [ ] [add_missing_match_arms](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/add_missing_match_arms.rs)
	- [x] diagnostic implemented, https://github.com/veykril/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-diagnostics/src/handlers/missing_match_arms.rs
	- Probably somewhat blocked on us improving our exhaustiveness checking. We also want to retain the ability to explode `_` patterns in matches
- [ ] [add_return_type](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/add_return_type.rs)
	- [ ] diagnostic implemented
	- Note that we want to retain the assist for closure return types as eliding them can be valid, yet sometimes we want to be able to explicitly annotate them
- [ ] [add_turbo_fish](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/add_turbo_fish.rs)
	- [ ] diagnostic implemented
	- turbo fishes can be elided in some occasions, so we want to also keep the assist for it 
- [ ] [auto_import](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/auto_import.rs#L34)
	- [ ] diagnostics implemented, this one is tough as unresolved names have many forms, so this will consist of a lot of different diagnostics
	- There is at least on occurence where no diagnostic will exist, yet the assist would be wanted, identifier patterns. Those don't usually generate diagnostics but could be part of a path or signal an unimported constant.
- [ ] [convert_into_to_from](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/convert_into_to_from.rs)
	- [ ] diagnostic implemented, should be a warning 
- [ ] [fix_visibility](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/fix_visibility.rs)
	- [ ] diagnostic implemented, like auto import, can have multiple sources
- [ ] [generate_constant](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/generate_constant.rs)
	- [ ] diagnostic implemented
- [ ] [generate_function](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/generate_function.rs)
	- [ ] unresolved function diagnostic implemented
	- [x] unresolved method diagnostic implemented
- [ ] [remove_unused_param](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/remove_unused_param.rs)
	- [ ] diagnostic implemented
- [ ] [unnecessary_async](https://github.com/rust-analyzer/rust-analyzer/blob/e6ba791dcecfb2d69e831e204f06f2d3bf86323a/crates/ide-assists/src/handlers/unnecessary_async.rs)
	- [ ] diagnostic implemented

> The assist checkbox is for when the assist code has been turned into the diagnostics quickfix
