### ISSUE TITLE
Steering Issue 18

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15092]
[Zulip meeting](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Steering.20meeting/near/367670862)
Previous issue: https://github.com/rust-lang/rust-analyzer/issues/13657
- @Veykril 
  - [ ] investigate/implement support for attributes and aliases on use and extern crate items https://github.com/rust-lang/rust-analyzer/issues/14079
  - [ ] token-map rewrite https://github.com/rust-lang/rust-analyzer/issues/9403
- @lnicola 
  - [ ] investigate compression for in-memory files https://github.com/rust-lang/rust-analyzer/issues/869
- [x] setup proper zulip group
- [x] merge the two rust-analyzer teams into one
- [ ] think about how to solve https://github.com/rust-lang/rust-analyzer/issues/14846
- [ ] investigate improvements for our VFS impl
