### ISSUE TITLE
Steering Issue 19

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15596]
[Zulip meeting](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Steering.20meeting/near/367670862)
Previous issue: https://github.com/rust-lang/rust-analyzer/issues/15092
- @Veykril 
  - [ ] investigate/implement support for attributes and aliases on use and extern crate items https://github.com/rust-lang/rust-analyzer/issues/14079
  - [x] token-map rewrite https://github.com/rust-lang/rust-analyzer/issues/9403
- @lnicola 
  - [ ] investigate compression for in-memory files https://github.com/rust-lang/rust-analyzer/issues/869
- [ ] think about how to solve https://github.com/rust-lang/rust-analyzer/issues/14846 / https://github.com/rust-lang/rust-analyzer/issues/15569
- [ ] investigate improvements for our VFS impl

**Comment by jmintb** [comment]
I am up for investigating improvements to the VFS impl if there are any ideas/problems that you have in mind and want to delegate :)
