### ISSUE TITLE
Meta feature: Language server support for `Cargo.toml` file

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust-analyzer#15741]
This issue is an attempt to put all information regarding potential `Cargo.toml` support in one place.

## Blockers

There is no TOML support in RA, and needs a format-preserving parser. [`toml-edit`](https://github.com/toml-rs/toml) is maintained along with `toml` and probably the best choice.

## Potential features

- [ ] Autocomplete or schema help (reference: https://doc.rust-lang.org/cargo/reference/manifest.html)
  - [ ] Autocomplete keys
  - [ ] Suggest valid values for fixed keys like `edition`, `rust-version`, `license`
  - [ ] Suggest in-workspace files for `license-file`, `readme`, `build`
  - [ ] Autocomplete dependencies
  - [ ] Autocomplete dependency features
 - [ ] Schema validation and warnings/errors, based on the above
- [ ] Quick actions & refactoring
  - [ ] "Move feature to `dev-dependencies`/`dependencies`/`build-dependencies`"
  - [ ] "Update crate to latest compatible version"
  - [ ] "Update crate to latest incompatible version"
  - [ ] Toggle `no-default-features`
  - [ ] Refactor simple dependencies to objects and back, like RustRover does
  ![image](https://github.com/rust-lang/rust-analyzer/assets/13724985/a15890b7-9bc6-4e4a-94bb-be35df636be2) 
- [ ] Link to crates like the `crates` extension: https://github.com/rust-lang/rust-analyzer/issues/13532
- [ ] Add crates to `Cargo.toml` from a use statement #10904
- [ ] Add syntax highlighting to TOML files #3565. I think the syntax highlighting is not much of a concern since `Even better TOML` does it well, but there are some good general suggestions in the issue

See the label https://github.com/rust-lang/rust-analyzer/labels/S-needs-toml

**Comment by obsgolem** [comment]
My issue https://github.com/rust-lang/rust-analyzer/issues/10117 needs the needs-toml label.

**Comment by tgross35** [comment]
> My issue #10117 needs the needs-toml label.

Thanks for the link, I added it to the list

**Comment by alibektas** [comment]
I want to point out that I am indirectly working on this issue. I am trying to implement a `.rust-analyzer.toml` (#13529) file support. I hope to end up with an integrated TOML parser in ra although it is not my primary concern ( RATOML's first prototype won't be needing a TOML parser, ser-de should be enough for now). I would be happy if contributors to this issue could reach out to me so that we can talk about its implementation.

**Comment by tgross35** [comment]
@alibektas that sounds very cool!

I think that `toml-edit` is more or less a drop in for `toml` and works with the same structs with Serde. The difference is that the untyped representation (`toml_edit::Document`, a strict superset of `toml::Value`) has support for format preservation. Maybe it makes sense to prototype with `toml-edit` instead of the usual `toml` just so its use can be expanded in the future?

Not that I expect RA would be editing `.rust-analyzer.toml` ever, but it could make sense for any framework that will eventually be shared with `Cargo.toml`

**Comment by alibektas** [comment]
:wave:  

There are couple of things that I first need to look into before giving you an answer.

1) Will RA maintainers be OK with `toml-edit` being included in RA? The impression that I got thus far is that we are very conservative when it comes to using external crates. ( This I will be asking Vekyril next week )

2) How well will `toml-edit` be compatible with RA's incremental computation principles? ( This is a concern that goes beyond the prototyping phase. ) 
  
For the prototype your proposition seems to be the way to go, but this is just me speaking without having really looked at `toml-edit` in depth. I will get back to you with a more detailed answer possibly next week, but let me at least say that I agree `toml-edit` being better in this regard than `toml`.

**Comment by Veykril** [comment]
Fwiw, we most likely want to end up with a toml parser thats built on top of rowan, which kind of exist https://docs.rs/taplo/latest/taplo/ so we probably want to strip that down.

**Comment by alibektas** [comment]
@tgross35 :wave: I think Veykril's reply answers the greater part of your question, but I think it all comes down to determining how long it will take us to integrate the said taplo crate to RA.

**Comment by wyatt-herkamp** [comment]
This is a feature I would really like to see. I was debating building a separate plugin to some of the features listed.

 Is this a feature that RA will accept into its code base? 

if So I would be interesting in starting to add it to RA?

**Comment by Veykril** [comment]
Definitely something we want to have, its just a lot of work and requires some other things to be done first, like creating / integrating a rowan based syntax library for toml -> https://github.com/rust-lang/rust-analyzer/pull/15908
