### ISSUE TITLE
Implement the remaining unimplemented proc-macro APIs in the proc-macro server

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15950]
Note: This will have to wait until after my token map rewrite.

We have no issue tracking this yet so I figured making a barebones one should be good for any discussions involved as it is already known that this is gonna be a difficult thing to do.

To describe the problem in simple terms, a lot of the API exposes state of the world to proc-macros, an example being asking for the [source of a span](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.source_text). In rustc, this is fine as the proc-macro server runs inside the main rustc process, but in rust-analyzer, the server is a separate process that rust-analyzer communicates to via a a json RPC interface. This worked out fine so far as we only need to ask the server to expand a proc-macro with a given token stream and giving back the expanded one. To serve these unimplemented APIs otoh, we need to allow the server to communicate back to the client (rust-analyzer) to ask for certain information / properties about the program (and potentially in the future even ask about [expanding macros](https://doc.rust-lang.org/proc_macro/struct.TokenStream.html#method.expand_expr) which requires name resolution 😭). In theory, this should be straight forward but we might run into problems wrt the client-server architecture of the proc-macro bridge. That's the main open question to solve once this is being worked on.

**Comment by ChayimFriedman2** [comment]
Unimplemented proc_macro APIs:

 - [ ] [Diagnostic APIs](https://doc.rust-lang.org/nightly/proc_macro/struct.Diagnostic.html)
 - [ ] [`expand_expr()`](https://doc.rust-lang.org/nightly/proc_macro/struct.TokenStream.html#method.expand_expr)
 - [ ] [`Span::file()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.file), [`Span::local_file()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.local_file), [`Span::line()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.line), [`Span::column()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.column), [`Span::byte_range()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.byte_range)
 - [ ] [`Span::source_text()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.source_text)
 - [ ] [`Span::source()`](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.source)
