### ISSUE TITLE
Imrpoved CFG experience

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16346]
Currently working with `#[cfg(...)]`'ed code in r-a is not a nice experience, it's difficult to switch between them (or in part just impossible currently) and otherwise annoying, with semantic highlighting for example unconfigured code just turns into a bunch of random colors due to not having semantic information.

We should be able to do better here, the question is to what degree! Here a bunch of issues that are related to that experience (there are more smaller IDE related issues aside from the listed ones)

- [ ] https://github.com/rust-lang/rust-analyzer/issues/16191
- [ ] https://github.com/rust-lang/rust-analyzer/issues/16122
- [ ] https://github.com/rust-lang/rust-analyzer/issues/15352
- [ ] https://github.com/rust-lang/rust-analyzer/issues/12462
- [ ] https://github.com/rust-lang/rust-analyzer/issues/5421
- [ ] https://github.com/rust-lang/rust-analyzer/issues/12059
- [ ] https://github.com/rust-lang/rust-analyzer/issues/6117
- [ ] https://github.com/rust-lang/rust-analyzer/issues/4041

It mainly boils down to two core issues,
- [ ] being able to switch between configurations dynamically without fiddling with settings and having to restart the server, and
- [ ] Giving a better user experience for unconfigured code

The former seems like simpler issue to solve, it mainly requires some UX design and integration part, the second on the other hand is more tricky and needs some architecture thinking.
