### ISSUE TITLE
Steering Issue 21

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18479]
[Zulip meeting](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Steering.20meeting/near/367670862)
Previous issue: https://github.com/rust-lang/rust-analyzer/issues/16013
- [ ] land the new salsa
    - [ ] slowly migrate away from the transition macro to native salsa features
    - [ ] move interning of type IR to chalk (merge once salsa has GC)
- [ ] look more into the new trait solver
- [ ] move more assists to syntax editor https://github.com/rust-lang/rust-analyzer/issues/18285
- [ ] Check the 2024 edition, see what we are missing https://github.com/rust-lang/rust-analyzer/issues/16146 (issue is not complete)

**Comment by ChayimFriedman2** [comment]
@Ten0  It's not just potential, it's pretty much guaranteed. Chalk is no longer developed and the new trait solver is supposed to replace both rustc's old trait solver and Chalk in r-a.

The new trait solver is supposed to be more efficient than Chalk (especially given it will also be used in rustc, which means it will see heavy perf work, something Chalk didn't have), but that doesn't necessarily mean it will solve your problem. We will have to wait and see.
