### ISSUE TITLE
Tracking issue for Edition 2021 support

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#9056]
This is a list of 2021 edition changes that require rust-analyzer support. The list is taken from the official blog post https://blog.rust-lang.org/2021/05/11/edition-2021.html.

* [x] Edition-dependent prelude (not fully implemented upstream: https://github.com/rust-lang/rust/pull/85687) – implemented in #9097
* [x] `IntoIterator` for arrays (will be supported automatically, but needs https://github.com/rust-analyzer/rust-analyzer/issues/8552 to correct behavior on 2015/2018 editions)
* [x] Panic macro consistency – implemented in https://github.com/rust-analyzer/rust-analyzer/pull/8304
* [ ] Reserve literal prefixes (upstream seems to not have fully agreed on an implementation strategy at this point)
* [x] Or-patterns in `macro_rules` – tracked by https://github.com/rust-analyzer/rust-analyzer/issues/9055

**Comment by m-ou-se** [comment]
> Edition-dependent prelude (not fully implemented upstream: rust-lang/rust#85687)

Note that the three `std::prelude::rust_*` modules already exist and the right one is already selected based on the edition. So, rust-analyzer could already implement picking the right prelude. It's just that right now all three of these modules have identical contents, until that PR is merged.
